sudo: required
cache: pip
language: python
python:
  - "3.6"

env:
  global:
    secure: "kG19tkU4gN4i2l0rgEs5+Q8eFgptbEnybpaGrMfXF8FGcrDSiNPvmGQ2T9/YiBnsWftgqUsiW4VeXfb1EDkq4FLWadCgX/hKbKxtzUI9dY1aJE6J53yfxaD5/H3eOWoBwRDelgSjPayAoB3KHWDVGN80jCysB4olivZgDS6JsOCxhhY0MSfVxYUV8DjbwJ8wLlyHiX2YiYlo4Na7nJKtrNvs8RHxtoatC/TsUyj13KAp7GjdGSL2Ev/GYecECqKwI+6iISoi7Y7l9r8sTO4K6PCudIhxdgpdnqwz1sPJ88q+GNUSmqeohPyR7YwQCWF0JAUHWdn18acmrr+rUgKFvW34AuftjammB1l6KxHa32UpCJ9qXBoDXnREjxPDYvkYi/RSVGtfabKaMVz/pOgpYtstO20glVfKFCrmO+dUyJ2Hoh5ekjvr31O9jM8/1EWal2IHFQmomy8XSsZ/9Tt2tMO3H0u/SVs1OALPJFokt4d9WsKD6oOb9KgQMQuOhwgpKeHafP0+ZbXdqZepaW7zscIvhXk0j8gUclhVsweLf0itxl4C70tYtaB45quuw8Aha6cKspHkkqpFFLogtSasElucmbStkR1Xq5G7PuVf4cIDFTxSNpGUxa4kX7qSfPZK0l2QbZG/IeJQurkdhYczJi3G/ZeTn6sCGylb64GpCdU="
    secure: "JohMWQDrprcOgxL7STLuBJz8Te7e1dKnYWcFKF1sHxccjNfMfgIxxRPD0BaHyECiU/SZxZa94gYSvc4/y5r0d3j27djtXXJc5w48o8sv3lLnonrJsr7F2ldnDIgGRRoV3/NciW4hsCLPNO5C4D9E/I+uP3QEIaBcQ+vom44MizlxPydNsTWDGnO71JHJVzE9+EXUvx2KtIxbIr9uIfHhOkgevHzQ3AG9iw6gRqmZyapCbfHm88h4HGxLXoUTB8nGY7yIWed3F27R5hohSmojr5NqNItWaau+Jh7c1b51qNYDL4f3xlE1MrZpo7Tei/rlZtJbsGRBXVq1nQWwJOq1/uEDwIriLAo86l0F88qGEJinc7Wyx3GYPHleUZWjD/uF+LH2rhwdYvzsqD71zNmgGC91Nk7+ZuVcPTNNh2Vufk9fqd1PndJHWHePS7GBQX8bb9ZZFVpe7hG7Qitb/pUlpF7B4QIeAxRvEhuaxJdxpms3t55N2UYg0INeqZfcKtcU3pENNNBL6USz7ka2IdjMfZQvfiybWrSy7fr3ueq1jBEEPghjvGyWA+tHWhAy/QVbETpZDP7rolG1YWXMuPUqAEXFpwap+JeHO0n7uG5h68d0o9QIUAVp0kcyAz3M4nPfHtmmbcc7td2soEx84RtnJ7/6igpqI2mnmaZ06uhzqkM="

services:
  - docker
  - postgresql

install:
  - pip install -r requirements.txt -r test-requirements.txt
  - pip install coveralls

script: tox

after_success:
  - coveralls
  - export REPO=girleffect/core-access-control
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH_CLEAN ; fi`
  - docker build -t $REPO:$TAG .

deploy:
  provider: scrip
  script: bash docker_push
  on:
    branch: develop
