sudo: required
cache: pip
language: python
python:
  - "3.6"

env:
  global:
    secure: "P+b5lplZJd8835q4DPQYXCpeXwt7+YznBdFoUqu0vwZDRXfX1e5Kbm9dcyxcXfUmeTcXnQVx1JKRh1jorV0bG4ZaFc2uo6WqyQ1m9izzopjAuOwsnhj3Q2Xnuc8PBninEU5n1ood0VPuhtz/jP3cy9FrGGqoa/DLXT8NIURvbPoG/jqhq2LrHlBdW0HtygZjhqULXfqzm+bzqKHDVMalhs2l4HsRkjojO7BpgbBS6c861fWIji2o068yP7YSoWxJyXUp2InDvm+oCU+5pMl3Hsb6/6vayPzH+OtiaFDog6RPLBEhmlgaecF1Y+q4N1t5vpk6ATlzGLscX2qb0xX4i0PDT0skqw1hS87FGx/jyIgqPVx30fAfpCyaTO8YkVXy8yteDmYGm+uEA7RXWWLTXaL/IcXOe6+1Pwjl4BZ9s9nzBtkIoanBaTmB3xeaoHyNlRY8yJP3QfUmYSqndX86Qr2ASIK96YtL7qW0lrzuc1pxoEFtYDud5/cP3JM/SlIRinK2H+2REnmBP6h55M5sMiBHD5t7L0boej9w5WNZmJiXkMoAt8eYYf+xYDrngMpkPej802BFky0jVKS84QzPKGp/t8tfDr7AGcehLPjeFbpivldRFadD5GXdmswB/itg0Eyjrj164d7mt0oudCGQwk+DejctSI5Gs/TTPKjAtxo="
    secure: "BEFq8ivd1R+a6egmXRqSj0mc87e5jnbk0Qhhj9XmCwKCCKThozMURscw6X5D/2bM3lBs1EN6i0Hd3DluCCjps6J2wk4D3OZp2ltqWBD7cD5Ta7k5ySOBYY8D2IqMfyHJ/kcbyQbSbYTNDbGYY2XpUv3KQ3NbNha1LYVzyoywLp9au9b+VI/s/twWaApO1/3ls53stAg+qmjGR5wjcAl9hs9vwEGfMIPjDMRJuEW4S+pCIVC/7c/X3v8flDc0YBXhKRLeSdnbbjjtk6nzFznZ4jpdwuFWInpZcT9cziMUseNKNpl+Qm4BVEVqtCOqf+g6gYNLaSZcUY+8fXyr77VEUqoSxp05BTnzVt0L4lO3n72wtvTCWY18vZWsc0Yx525/f7ztaRSwhssKGFEiHboTnZ/UdssvahmecllZnyhmjXh0qdf9CftqPi6LPFPMdbGoEsE0w+2bc7ZPLJ2M+VQTVp2CAoyS0su2OFOHufG2F3szohfcnuu2EOffoyxMthHrXblMEZMZ/nYUqwQnEH4ofhCO/jae6cW712eyAfEao3YbqjVolwXSZJ8JHFzff9R1zsqhNdvUlyeFLpg+En5IrB6nxhUoSZYrL61BNqEdFb/WsNCu539SJ1rupjTL2Kvi6VmBb+9GyYF4IU2dvQrZMmHSYi0PQBHGnCcBzdAXT98="

services:
  - docker
  - postgresql

install:
  - pip install -r requirements.txt -r test-requirements.txt
  - pip install coveralls

script: tox

deploy:
  provider: script
  script: bash ./docker_push.sh

after_success:
  - coveralls
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH_CLEAN ; fi`
  - docker build -t girleffect/core-access-control:$TAG .
