sudo: required
cache: pip
language: python
python:
  - "3.6"

env:
  global:
    secure: "kG19tkU4gN4i2l0rgEs5+Q8eFgptbEnybpaGrMfXF8FGcrDSiNPvmGQ2T9/YiBnsWftgqUsiW4VeXfb1EDkq4FLWadCgX/hKbKxtzUI9dY1aJE6J53yfxaD5/H3eOWoBwRDelgSjPayAoB3KHWDVGN80jCysB4olivZgDS6JsOCxhhY0MSfVxYUV8DjbwJ8wLlyHiX2YiYlo4Na7nJKtrNvs8RHxtoatC/TsUyj13KAp7GjdGSL2Ev/GYecECqKwI+6iISoi7Y7l9r8sTO4K6PCudIhxdgpdnqwz1sPJ88q+GNUSmqeohPyR7YwQCWF0JAUHWdn18acmrr+rUgKFvW34AuftjammB1l6KxHa32UpCJ9qXBoDXnREjxPDYvkYi/RSVGtfabKaMVz/pOgpYtstO20glVfKFCrmO+dUyJ2Hoh5ekjvr31O9jM8/1EWal2IHFQmomy8XSsZ/9Tt2tMO3H0u/SVs1OALPJFokt4d9WsKD6oOb9KgQMQuOhwgpKeHafP0+ZbXdqZepaW7zscIvhXk0j8gUclhVsweLf0itxl4C70tYtaB45quuw8Aha6cKspHkkqpFFLogtSasElucmbStkR1Xq5G7PuVf4cIDFTxSNpGUxa4kX7qSfPZK0l2QbZG/IeJQurkdhYczJi3G/ZeTn6sCGylb64GpCdU="
    secure: "BEFq8ivd1R+a6egmXRqSj0mc87e5jnbk0Qhhj9XmCwKCCKThozMURscw6X5D/2bM3lBs1EN6i0Hd3DluCCjps6J2wk4D3OZp2ltqWBD7cD5Ta7k5ySOBYY8D2IqMfyHJ/kcbyQbSbYTNDbGYY2XpUv3KQ3NbNha1LYVzyoywLp9au9b+VI/s/twWaApO1/3ls53stAg+qmjGR5wjcAl9hs9vwEGfMIPjDMRJuEW4S+pCIVC/7c/X3v8flDc0YBXhKRLeSdnbbjjtk6nzFznZ4jpdwuFWInpZcT9cziMUseNKNpl+Qm4BVEVqtCOqf+g6gYNLaSZcUY+8fXyr77VEUqoSxp05BTnzVt0L4lO3n72wtvTCWY18vZWsc0Yx525/f7ztaRSwhssKGFEiHboTnZ/UdssvahmecllZnyhmjXh0qdf9CftqPi6LPFPMdbGoEsE0w+2bc7ZPLJ2M+VQTVp2CAoyS0su2OFOHufG2F3szohfcnuu2EOffoyxMthHrXblMEZMZ/nYUqwQnEH4ofhCO/jae6cW712eyAfEao3YbqjVolwXSZJ8JHFzff9R1zsqhNdvUlyeFLpg+En5IrB6nxhUoSZYrL61BNqEdFb/WsNCu539SJ1rupjTL2Kvi6VmBb+9GyYF4IU2dvQrZMmHSYi0PQBHGnCcBzdAXT98="

services:
  - docker
  - postgresql

install:
  - pip install -r requirements.txt -r test-requirements.txt
  - pip install coveralls

script: tox

deploy:
  provider: script
  script: bash ./docker_push.sh
  on:
    branch: $TRAVIS_BRANCH

after_success:
  - coveralls
  - export REPO=girleffect/core-access-control
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH_CLEAN ; fi`
  - docker build -t $REPO:$TAG .
